version: '3.9'

name: teddy-case

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "--username", "postgres" ]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 15s
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network

  nestjs-app:
    build: .
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    command: ["npm", "run", "start:prod" ]
    networks:
      - app-network

volumes:
  pg_data:
    driver: local

networks:
  app-network:
    driver: bridge